update=Thu 16 Oct 2014 08:02:14 AM EEST
last_client=kicad
[pcbnew]
[pcbnew/libraries]
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=smd_capacitors
LibName7=smd_resistors
LibName8=smd_transistors
LibName9=libcms
LibName10=display
LibName11=led
LibName12=dip_sockets
LibName13=pga_sockets
LibName14=valves
LibName15=./isp_side_connector
LibDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[general]
version=1
